sudo: false
language: ruby
rvm:
  - 2.5.1

notifications:
  email: false

matrix:
  fast_finish: true
  include:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: 2.5.1
      gemfile: Gemfile
    - rvm: 2.5.1
      gemfile: Gemfile
      env:
        - NO_RAILS=1
    - rvm: 2.4.3
      gemfile: Gemfile
    - rvm: 2.3.1
      gemfile: gemfiles/rails42.gemfile
  allow_failures:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
