sudo: false
language: ruby
cache: bundler

notifications:
  email: false

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'

matrix:
  fast_finish: true
  include:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: 2.7
      gemfile: Gemfile
    - rvm: 2.7
      gemfile: gemfiles/activedeliverymaster.gemfile
    - rvm: 2.6
      gemfile: Gemfile
    - rvm: 2.5
      gemfile: Gemfile
      env:
        - NO_RAILS=1
    - rvm: 2.5
      gemfile: gemfiles/rails52.gemfile
    - rvm: 2.5
      gemfile: gemfiles/rails42.gemfile
  allow_failures:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: 2.7
      gemfile: gemfiles/activedeliverymaster.gemfile
