sudo: false
language: ruby
cache: bundler

notifications:
  email: false

before_install:
  - gem update --system
  - gem install bundler -v '< 2'

matrix:
  fast_finish: true
  include:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
    - rvm: 2.5.3
      gemfile: Gemfile
    - rvm: 2.6.0
      gemfile: Gemfile
    - rvm: 2.5.3
      gemfile: Gemfile
      env:
        - NO_RAILS=1
    - rvm: 2.4.3
      gemfile: Gemfile
    - rvm: 2.4.3
      gemfile: gemfiles/rails42.gemfile
  allow_failures:
    - rvm: ruby-head
      gemfile: gemfiles/railsmaster.gemfile
